version: '3'

services:

  backend1:
    build: ./backend1
    ports:
      - "5001:5000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

  backend2:
    build: ./backend2
    ports:
      - "5002:5000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend1
      - backend2
